name: simplyreader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.1.4
  flutter_pdfview: ^1.3.4
  epubx: ^4.0.0
  syncfusion_flutter_pdfviewer: ^28.1.33
  epub_view: ^3.2.0
  pdf: ^3.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/simplyReaderIcon.png" # Use PNG instead of ICO
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/simplyReaderIcon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/simplyReaderIcon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/simplyReaderIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/simplyReaderIcon.png
